version: '3'
services:
  postgres:
    container_name: "postgres"
    image: "postgres:13.4-buster"
    restart: "always"
    networks: [ postgresNetwork ]
    environment:
      HTTP_PROXY:
      HTTPS_PROXY:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "imdbload"
    user: postgres
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
      - postgresVolume:/var/lib/postgresql/data   
    ports:
      - "5432:5432"

  virtuoso:
    container_name: "virtuoso"
    image: "minhhoangdang/virtuoso-csopts:latest"
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    ports:
      - '8890:8890'
      - '1111:1111'
      - '4000:4000'
    volumes:
      - '${VIRTUOSO_DB}:/root/virtuoso-opensource/database'
      - '/tmp:/tmp'
    command: bash -c "./virtuoso-t +configfile ../database/virtuoso.ini && flask run --host=0.0.0.0 --port=4000"
  
  sage-engine:
    container_name: sage-engine
    image: "minhhoangdang/sage-engine:py394-rlxp"
    ports:
      - '8081:8081'
    volumes:
      - ${SAGE_GRAPH}:/root/sage-engine/graphs
      - ${SAGE_CONFIG}:/root/sage-engine/config/sage.yaml
    entrypoint: 'conda run --no-capture-output -n xp /bin/bash -c "poetry run sage config/sage.yaml --workers=1 --port=8081"'
    #entrypoint: 'conda run --no-capture-output -n xp /bin/bash -c "sh launch.sh sage"'
    
  rtos:
    depends_on: 
      - postgres
    container_name: "rtos"
    build:
      context: .
      dockerfile: docker/rtos.Dockerfile
      network: "host"
      args:
        HTTP_PROXY:
        HTTPS_PROXY:
    environment:
      RTOS_JOB_DIR: "JOB-queries"
      RTOS_SCHEMA_FILE: "schema.sql"
      RTOS_DB_PASSWORD: "123456"
      RTOS_DB_USER: "postgres"
      RTOS_DB_NAME: "imdbload"
      RTOS_DB_HOST: "postgresql://${RTOS_DB_USER}:${RTOS_DB_PASSWORD}@postgres/${RTOS_DB_NAME}"
      RTOS_DB_PORT: "5433"
      RTOS_JTREE_BUSHY: 0 
      RTOS_ENGINE: "sparql"
    volumes:
      - ./models:/workplace/models
      - ./log:/workplace/log 
      - /tmp:/tmp
    networks: [ postgresNetwork ]

  jupyter-notebook:
    container_name: rtos-jupyter
    network_mode: "host"
    build: 
      dockerfile: docker/jupyter.Dockerfile
      context: .
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    entrypoint: 'jupyter notebook --allow-root --NotebookApp.allow_origin=https://colab.research.google.com --port=8080 --NotebookApp.port_retries=0'

networks:
  postgresNetwork:
    driver: bridge 

volumes:
  postgresVolume:
