name: SaGe experimental server
quota: 75
# max_results: 10000
stateless: True
graphs:
-
  name: jobrdf
  uri: http://localhost:8080/sparql/jobrdf
  backend: hdt-file
  file: /root/sage-engine/graphs/imdbfull.hdt
