cost-training:
  database:
    engine_class: sparql
    engine_name: "sage"
    syntheticDir: "Queries/sytheic"
    JOBDir: "JOB-queries/sparql"

    # Postgres
    pg_schema_file: "schema.sql"
    pg_password: "123456"
    pg_user: "postgres"
    pg_dbname: "imdbload"
    pg_host: "0.0.0.0"
    pg_port: "5432"

    # Virtuoso
    virtuoso_endpoint: "sparql"
    virtuoso_host: localhost
    virtuoso_graph: "http://example.com/DAV/void"
    virtuoso_port: 8890
    use_bushy_tree: false # Not available for sparql
    tree_num_in_net: 40

    # SaGe
    sage_endpoint: "sparql"
    sage_host: localhost
    sage_port: 8081
    sage_graph: "http://localhost:8081/sparql/jobrdf"
    sage_max_steps: 12000
    sage_convergence_threshold: 10
  
    # Experimental
    isql_featurization_v2: false
    
  model:
    # Featurization
    max_column_in_table: 15
    feature_size: 512
    n_words: 1000

    # Train
    name: "cost-training-50k"
    n_episodes: 50000
    data: sparql
    save_every: 1
    update_target_every: 3
    shuffle_train_every: 200
    rewarder: "refined-cost-improvement"
    device: cpu
    checkpoint: "checkpoint-50k.yml"

    # DQN
    dqn_adam_learning_rate: 0.0003
    dqn_memory_capacity: 10000
    dqn_max_action: 25
    dqn_eps_start: 0.4
    dqn_eps_end: 0.2
    dqn_eps_decay: 400
    dqn_batch_size: 1

  logging:
    debug: 0 # 0 = None, 1 = console, 2 = file
    use_wandb: false
    use_graphviz: false
    incl_mes: true
    incl_mrc: true
    incl_dqn_gd_time: true
    incl_reward: true

