SELECT * WHERE {

  # Value clauses
  VALUES ?mi_info { "Drama" "Horror" "Western" "Family" }

  # Join clauses
  ?mi <http://imdb.org/movie_info#movie_id> ?t .
  ?mi <http://imdb.org/movie_info#info_type_id> ?it1 .
  ?midx	<http://imdb.org/movie_info_idx#movie_id> ?t .
  ?midx <http://imdb.org/movie_info_idx#info_type_id> ?it2 .
  ?mc <http://imdb.org/movie_companies#movie_id> ?t .
  ?mc <http://imdb.org/movie_companies#company_type_id> ?ct .
  ?mc <http://imdb.org/movie_companies#company_id> ?c .

  # Shortcuts
  ?mc <http://imdb.org/movie_companies#movie_info#movie_id#movie_id> ?mi.
  ?mc <http://imdb.org/movie_companies#movie_info_idx#movie_id#movie_id> ?midx.
  ?mi <http://imdb.org/movie_info#movie_info_idx#movie_id#movie_id> ?midx.

  # Attribute selection clauses
  ?mi <http://imdb.org/movie_info#info> ?mi_info .
  ?midx <http://imdb.org/movie_info_idx#info> ?midx_info .
  ?c <http://imdb.org/company_name#name> ?c_name .
  ?t <http://imdb.org/title_t#title> ?t_title .
  ?t <http://imdb.org/title_t#production_year> ?t_production_year .

  # Filter clauses
  ?c <http://imdb.org/company_name#country_code> "[us]".
  ?ct <http://imdb.org/company_type#kind> "production companies".
  ?it1 <http://imdb.org/info_type#info> "genres".
  ?it2 <http://imdb.org/info_type#info> "rating".
  FILTER (str(?midx_info) > str("7.0")) .
  FILTER (?t_production_year >= 2000 && ?t_production_year <= 2010) .

}
