SELECT * WHERE {

  # Value clauses
  VALUES ?k_keyword {
    "murder-in-title" "murder" "blood" "violence"
  }
  VALUES ?kt_kind {
    "movie" "episode"
  }
  VALUES ?mi_info {
    "Sweden" "Germany" "Swedish" "German"
  }

  # Join clauses
  ?t <http://imdb.org/title_t#kind_id> ?kt.
  ?mk <http://imdb.org/movie_keyword#movie_id> ?t .
  ?mk <http://imdb.org/movie_keyword#keyword_id> ?k.
  ?mi <http://imdb.org/movie_info#info_type_id> ?it1.
  ?mi <http://imdb.org/movie_info#movie_id> ?t .
  ?midx <http://imdb.org/movie_info_idx#info_type_id> ?it2.
  ?midx <http://imdb.org/movie_info_idx#movie_id> ?t.
  ?mc <http://imdb.org/movie_companies#movie_id> ?t .
  ?mc <http://imdb.org/movie_companies#company_type_id> ?ct.
  ?mc <http://imdb.org/movie_companies#company_id> ?c.
  ?cc <http://imdb.org/complete_cast#movie_id> ?t .
  ?cc <http://imdb.org/complete_cast#subject_id> ?cct1.
  ?cc <http://imdb.org/complete_cast#status_id> ?cct2.

  # Shortcuts
  ?midx <http://imdb.org/movie_info_idx#movie_keyword#movie_id#movie_id> ?mk.
  ?mi <http://imdb.org/movie_info#movie_keyword#movie_id#movie_id> ?mk.
  ?mi <http://imdb.org/movie_info#movie_info_idx#movie_id#movie_id> ?midx.
  ?mc <http://imdb.org/movie_companies#movie_info#movie_id#movie_id> ?mi.
  ?mc <http://imdb.org/movie_companies#movie_keyword#movie_id#movie_id> ?mk.
  ?mc <http://imdb.org/movie_companies#movie_info_idx#movie_id#movie_id> ?midx.
  ?cc <http://imdb.org/complete_cast#movie_info#movie_id#movie_id> ?mi.
  ?cc <http://imdb.org/complete_cast#movie_keyword#movie_id#movie_id> ?mk.
  ?cc <http://imdb.org/complete_cast#movie_companies#movie_id#movie_id> ?mc.
  ?cc <http://imdb.org/complete_cast#movie_info_idx#movie_id#movie_id> ?midx.

  # Attribute selection clauses
  ?cct2 <http://imdb.org/comp_cast_type#kind> ?cct2_kind .
  ?c <http://imdb.org/company_name#country_code> ?c_country_code .
  ?k <http://imdb.org/keyword#keyword> ?k_keyword.
  ?kt <http://imdb.org/kind_type#kind> ?kt_kind.
  ?mi <http://imdb.org/movie_info#info> ?mi_info .
  ?mc <http://imdb.org/movie_companies#note> ?mc_note.
  ?midx <http://imdb.org/movie_info_idx#info> ?midx_info .
  ?t <http://imdb.org/title_t#production_year> ?t_production_year .
  ?c <http://imdb.org/company_name#name> ?c_name.
  ?t <http://imdb.org/title_t#title> ?t_title.

  # Filter clauses
  ?it1 <http://imdb.org/info_type#info> "countries".
  ?it2 <http://imdb.org/info_type#info> "rating".
  ?cct1 <http://imdb.org/comp_cast_type#kind> "crew".
  FILTER (?cct2_kind != "complete+verified").
  FILTER (str(?c_country_code) != "[us]").
  FILTER (str(?midx_info) > str("6.5")).
  FILTER (?t_production_year > 2005).
  FILTER (!regex(?mc_note, '\\(USA\\)') && regex(?mc_note, '\\(200.*\\)')).

}
