SELECT * WHERE {

  # Join clauses
  ?mk <http://imdb.org/movie_keyword#keyword_id> ?k .
  ?mk <http://imdb.org/movie_keyword#movie_id> ?t .
  ?ci <http://imdb.org/cast_info#movie_id> ?t .
  ?ci <http://imdb.org/cast_info#person_id> ?n .

  # Shortcuts
  ?ci <http://imdb.org/cast_info#movie_keyword#movie_id#movie_id> ?mk.

  # Attribute selection clauses
  ?n <http://imdb.org/name__t#name> ?n_name.
  ?t <http://imdb.org/title_t#production_year> ?t_production_year .
  ?t <http://imdb.org/title_t#title> ?t_title.

  # Filters
  ?k <http://imdb.org/keyword#keyword> "marvel-cinematic-universe" .
  FILTER regex(?n_name, "Downey.*Robert") .
  FILTER (?t_production_year > 2010) .

}
