SELECT * WHERE {

  # Join clauses
  ?an <http://imdb.org/aka_name#person_id> ?n.
  ?ci <http://imdb.org/cast_info#person_id> ?n.
  ?ci <http://imdb.org/cast_info#movie_id> ?t .
  ?mc <http://imdb.org/movie_companies#movie_id> ?t.
  ?mc <http://imdb.org/movie_companies#company_id> ?c.
  ?ci <http://imdb.org/cast_info#role_id> ?rt.

  # Shortcuts
  ?an <http://imdb.org/aka_name#cast_info#person_id#person_id> ?ci.
  ?ci <http://imdb.org/cast_info#movie_companies#movie_id#movie_id> ?mc.

  # Attribute selection clauses
  ?mc <http://imdb.org/movie_companies#note> ?mc_note.
  ?n <http://imdb.org/name__t#name> ?n_name.
  ?an <http://imdb.org/aka_name#name> ?an_name.
  ?t <http://imdb.org/title_t#title> ?t_title.

  # Filter clauses
  ?ci <http://imdb.org/cast_info#note> "(voice: English version)" .
  ?c <http://imdb.org/company_name#country_code> "[jp]" .
  ?rt <http://imdb.org/role_type#role> "actress".
  FILTER (regex(?mc_note, '\\(Japan\\)') && !regex(?mc_note, '\\(USA\\)')).
  FILTER (regex(?n_name, "Yo") && !regex(?n_name, "Yu")) .

}
