SELECT * WHERE {

  # Join clauses
  ?ci <http://imdb.org/cast_info#movie_id> ?t .
  ?ci <http://imdb.org/cast_info#role_id> ?rt.
  ?ci <http://imdb.org/cast_info#person_id> ?n.
  ?ci <http://imdb.org/cast_info#person_role_id> ?chn.
  ?mc <http://imdb.org/movie_companies#movie_id> ?t.
  ?mc <http://imdb.org/movie_companies#company_id> ?c.
  ?an <http://imdb.org/aka_name#person_id> ?n .

  # Shortcuts
  ?ci <http://imdb.org/cast_info#movie_companies#movie_id#movie_id> ?mc.
  ?an <http://imdb.org/aka_name#cast_info#person_id#person_id> ?ci.

  # Attribute selection clauses
  ?mc <http://imdb.org/movie_companies#note> ?mc_note.
  ?n <http://imdb.org/name__t#name> ?n_name.
  ?an <http://imdb.org/aka_name#name> ?an_name.
  ?chn <http://imdb.org/char_name#name> ?chn_name.
  ?t <http://imdb.org/title_t#title> ?t_title.
  ?t <http://imdb.org/title_t#production_year> ?t_production_year.

  # Filter clauses
  ?ci <http://imdb.org/cast_info#note> "(voice)" .
  ?c <http://imdb.org/company_name#country_code> "[us]" .
  ?n <http://imdb.org/name__t#gender> "f".
  ?rt <http://imdb.org/role_type#role> "actress".
  FILTER regex(?mc_note, '\\(200.*\\)').
  FILTER (regex(?mc_note, '\\(USA\\)') || regex(?mc_note, '\\(worldwide\\)')).
  FILTER regex(?n_name, "Angel").
  FILTER (?t_production_year >= 2007 && ?t_production_year <= 2010) .

}
